# Generated by Django 3.2.4 on 2021-06-20 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название болезни')),
                ('description', models.CharField(max_length=256, verbose_name='Описание болезни')),
                ('criteria', models.ManyToManyField(related_name='diseases', to='info.Criteria', verbose_name='Критерии')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код МКБ-10')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='info.disease', verbose_name='Болезнь')),
            ],
        ),
    ]
